### ISSUE TITLE
static and dynamic tabs is not working

### ISSUE THREAD

**Issue by Shemesh** [mikejacobson/angular-bootstrap-scrolling-tabs#11]
hi,
@mikejacobson 

when trying to use this (awesome) control in our project i encountered a problem and need your help, PLEASE.

i wrap a tabset that have some tabs that have ng-if on them. when the time comes to show those tabs i get the notorious tabContentTransclude error.
i have made a simple plunkr (forked from yours): http://embed.plnkr.co/VDWTrRF7dgYMT19ZY4uN/preview

note what happens when you click the "don't panic" button, look at the console.
how can i solve this?

p.s. moving all the tabs to an array to watch them is not an option for me.

TNX.

**Comment by Shemesh** [comment]
@mikejacobson 

just any idea - how about watching (angular $watch) the html that is generated for each tab.
for example get the div with class "tab-content" and watch when its children is changed. 

cont':
seems like using watch is a bad idea
https://github.com/angular/angular.js/issues/10522#issuecomment-67619184

but maybe some other way to watch for dom changes?

**Comment by mikejacobson** [comment]
@Shemesh, v0.0.20 should fix this.

Here's a fork of your plunk showing it working:
http://plnkr.co/edit/575H1Br10RhX5fNQ5mnB

You just need to add attribute `watch-tabs="true"` to the `scrolling-tabs-wrapper` element and it will set up watches on the DOM itself rather than on the tabs array.

Thanks for your suggestion and the follow-up information regarding watching the DOM. Unfortunately, I had to do it that way because the only alternative that I can think of would be to require you to set some specific flags in your code (which I would have watches set on) whenever you add/remove tabs or click to activate a different tab, and that didn't seem like a very reasonable solution. If it seems to be a performance problem, let me know.
