### ISSUE TITLE
horizontal line is not spread on whole width

### ISSUE THREAD

**Issue by Shemesh** [mikejacobson/angular-bootstrap-scrolling-tabs#13]
hi,
@mikejacobson 

when there are only few tabs, and the scroll buttons are hidden, the horizontal line (just below the tab headers) is not being spread to the whole width, but instead it is being terminated at the last tab.

**Comment by mikejacobson** [comment]
Hi Shemesh,

v0.0.19 should fix this issue.

It also contains a possible fix for your issue #11. It worked when I ran it locally but it wasn't working quite right in the fork of your plunk that I made:
http://plnkr.co/edit/575H1Br10RhX5fNQ5mnB

With the new scrolling-tabs.js, you just need to add `watch-tabs="true"` to the `scrolling-tabs-wrapper` element and it will refresh things when tabs are added or removed via `ng-if`.

So when you click the "don't panic" button, the error isn't thrown anymore and the additional tabs display. But the problem--in the plunk, anyway--is that selecting a tab doesn't always work. It seems like it only registers that you selected a tab every _other_ time. Strange, especially since it works fine running locally. So I'm still looking into it, but you can give it a try and see if it works for you.

Mike
