### ISSUE TITLE
Parent component not resizing correctly after tab content load

### ISSUE THREAD

**Issue by lmendezr** [mikejacobson/angular-bootstrap-scrolling-tabs#21]
Hello Mike,

I'm currently experiencing issues when placing the scrolling-tabs-wrapper inside a bootstrap panel-body. Upon further inspecting of `<div scrolling-tabs-wrapper>` I found out that only the tab header strip is being reported back to the parent without including it's contents. I'd say it has to do with the `.scrtabs-tab-content-outside-movable-container` method in the css file, but tbh I'm no css expert.

Here is an example scenario in which I'm using scrolling tabs:

``` javascript
<div class="panel-body">
    <div scrolling-tabs-wrapper watch-tabs="tabsCtrl.tabs" scroll-to-tab-edge="true">
        <tabset>
             <tab ng-repeat="tab in tabsCtrl.tabs" heading="{{tab.header" active="tab.active" disabled="tab.disabled" select="tabsCtrl.tabChanged(tab._id)">
                <ul class="list-group">
                    <a class="list-group-item"  ui-sref="items.view({itemID: item._id})" ng-repeat="item in tabsCtrl.items">
                        {{item.content}}
                </ul>
            </tab> 
        </tabset>
    </div>
</div>
```

Let me know if I'm doing something wrong in my side, or whether this might be a potential issue for ngscrollingtabs. Thanks!

**Comment by mikejacobson** [comment]
Does it actually work without scrolling-tabs-wrapper? Because it looks like there are some issues in the markup you posted. For example, inside the `<ul>` there are no `<li>` elements, just `<a>`s. And on the `<tab>` element with `ng-repeat`, the `heading` attribute value has opening double-curlies but no closing ones. 

It would help if you could put together a plunk or fiddle showing it working without scrolling-tabs-wrapper so I can try to diagnose the issue. Just being inside a Bootstrap panel-body shouldn't cause problems, I wouldn't think--the `panel-body` class just adds some padding around it, so there's probably something else going on.

Here's a plunk showing it working inside a panel-body:
http://plnkr.co/edit/lxrgqPlbAYmuid7lvpQJ?p=preview

It looks silly with the padding around it, but it still functions.

**Comment by lmendezr** [comment]
That's correct, it is working without the scrolling-tabs-wrapper. The markup I posted uses `<a>` instead of `<li>` because they are selectable items. This is where `<a class="list-group-item">` is your friend in Bootstrap, acting as a `<li>`, but giving you that "clickable list item" feel with a hover effect. 

Here's a forked plunk of yours pointing out the current issue I'm having. 
http://plnkr.co/edit/XAGLBRHq7gRitxuAIAqH?p=preview

I even used `<li>` inside of the `<ul>` and the issue seems to be the same. Content inside of the scrolling-tabs-wrapper will not have an issue rendering correctly, but anything outside of it will be rendered incorrectly. However, take the scrolling-tabs-wrapper out of the div and everything will be rendered correctly.

Also, here's a plunk with something closer to what I'm trying to achieve:
http://plnkr.co/edit/vYXB3Bb3w5WMrywJR4rR?p=preview

For now I managed to fix it by hardcoding a minimum height to the class, i.e. `<div class="panel-body" style="min-height: 800px; max-height: 800px;">`, but yeah, it tends to break if you resize the app, thus not making the best out of bootstrap.

Hope this helps, and thanks for following up Mike!

**Comment by mikejacobson** [comment]
Thanks for the plunks! That helped a lot. v0.0.24 should fix the issue.

Here are forks of your two plunks plunks showing it working:
http://plnkr.co/edit/LHNvWEAqmArD3zOfCK6t?p=preview
http://plnkr.co/edit/vh42q4NTY63SD6KvyTsr?p=preview

And just as a side-note, if your Bootstrap list-group contains links instead of `<li>`s, the parent element should be a `<div>` rather than a `<ul>`. Per the [list-group documentation](http://getbootstrap.com/components/#list-group-linked):

> Linkify list group items by using anchor tags instead of list items (that also means a parent <div> instead of an <ul>).

Let me know if you have any more issues. Thanks for using it!

**Comment by lmendezr** [comment]
Thanks a lot for the fix, Mike! Also for the side-note, guess I was just copy-pasting that aspect from the theme I was using, thus replicating the theme maker's mistake. I'll switch those `<ul>`'s to `<div>`'s now. Again, thanks, and have a nice one!
