### ISSUE TITLE
Lib places tab content twice

### ISSUE THREAD

**Issue by noherczeg** [mikejacobson/angular-bootstrap-scrolling-tabs#25]
Hey!

I'm experiencing a troublesome bug where the scrolling tabs lib creates the contents of a tab two times. This is problematic because components inside the tabs are making REST requests for reasons. This is originally not noticeable on screen because you hide the second one with CSS.
- scrtabs-tabs-fixed-container
- scrtabs-tab-content-outside-movable-container

The DOM looks like this:

![sample dom](http://i.imgur.com/fnJqtXa.png)

I don't know why is there a transcluded version and a non transcluded version as well, so I continue debugging.

**Comment by mikejacobson** [comment]
To support wrapping angular-ui tabs in situations where the tabs change after page load, the `.tab-content` needs to remain a sibling of the `ul.nav-tabs` due to directive dependencies that angular-ui creates, otherwise it throws an error when the tabs change (I think this was brought to my attention in issue #17).

Normally the `ul.nav-tabs` would live inside the movable container and the `.tab-content` would live outside the movable container, but unfortunately they can't be separated in this situation because of the angular-ui dependencies, so we need two instances of them.

If you don't need to watch the tabs for changes, then the `.tab-content` will be moved outside of the movable container, so there will only be one instance of it. But if you do need to watch the tabs for changes, unfortunately there will need to be two instances.

Sorry about that. Maybe you can detect the element's visibility or position in the DOM before making the REST request?

**Comment by noherczeg** [comment]
Thanks for the reply!

We have forms inside tabs which have components that fetch/pre-load data on their own. I believe watch is not used in our case:

```
<div ng-if="item.containerType === 'tab'" class="judo-scrolling-tab-wrapper">
        <div scrolling-tabs-wrapper judo-tab-scroll-arrow-override>
            <uib-tabset>
                <uib-tab ng-repeat="tabItem in item.items" heading="{{ tabItem.id | translate }}" active="vm.tabActivate[tabItem.id]" judo-tabs-id-appender="">
                    <div class="clearfix"></div>
                    <!-- Content resides here -->
                </uib-tab>
            </uib-tabset>
        </div>
</div>
```

**Comment by noherczeg** [comment]
"Sorry about that. Maybe you can detect the element's visibility or position in the DOM before making the REST request?"

I'd rather not do things like this. The whole linking, compiling watching shebang would fire anyway in the container area.

The tab container section should not take part in the tab calculations imho.

**Comment by mikejacobson** [comment]
I've looked into this a bit more and I think I have a fix. It looks like the `scrtabs-tab-content-outside-movable-container` element isn't even necessary anymore--the changes I've made over time have made that element obsolete--and with the removal of that, your double REST requests go away.

I should be able to commit the fix tonight after I get home and do a little more testing to make sure it doesn't break some scenario I'm not thinking about right now. In the meantime, though, if you can't (or don't want to) wait for the fix, you can just delete or comment out the `<div class="scrtabs-tab-content-outside-movable-container" ng-transclude></div>` line in the `scrollingTabsWrapperTemplate` definition (~line 59) in `scrolling-tabs.js`.

**Comment by noherczeg** [comment]
Tomorrow (GMT+1) I'll try it out, and come back with a response. Thanks for all the replies! :)

**Comment by noherczeg** [comment]
I removed the line you suggested, but the content is now gone entirely. The movable container seems to have the content, while the fixed container has the tabs (sadly with the contents as well).

**Comment by noherczeg** [comment]
I think that `div.scrtabs-tabs-fixed-container > div.scrtabs-tabs-movable-container > div > div.tab-content` is the problematic thing here. Based on the fact that it is invisible.

**Comment by mikejacobson** [comment]
Yeah, sorry about that--there was one other piece to that fix for your scenario.

I just committed v0.0.28, which should hopefully fix things for you.

**Comment by noherczeg** [comment]
Ohh, nice! I'll check it out in a few hours!

**Comment by noherczeg** [comment]
It seems to me that it works perfectly now. Thank you for your support!

**Comment by mikejacobson** [comment]
Stupendous! Glad it worked out.
