### ISSUE TITLE
Button click inside tab content is not firing with angular ui bootstrap

### ISSUE THREAD

**Issue by dev-thinks** [mikejacobson/angular-bootstrap-scrolling-tabs#28]
I have a dynamic angular uib-tabs which is working fine with scrolling tabs. it has dynamic tab content, button is one of them which is having click event. this button is not firing the event when placing inside scrolling tabs; works fine when removing this scrolling tab wrapper directive.

Anything am missing. any help is appreciated. 
Here is the plunk having issue with button click event inside tab content - 
http://plnkr.co/edit/FZo7R5?p=preview

**Comment by mikejacobson** [comment]
Thanks for making a plunk that demonstrates the issue--that makes it a lot easier to debug.

I think the problem is with the visible `.tab-content` being a clone of the original `.tab-content` (which is hidden inside the `.scrtabs-tabs-movable-container` to preserve the AngularUI directive dependencies), and losing the angular hooks in the cloning process.

It's strange because the buttons still recognize the `main` controller on their scope, but the click handler just isn't firing, so I'm thinking it got removed from the angular digest cycle.

I'll look into it.

**Comment by mikejacobson** [comment]
Sorry this took so long, and you've probably moved on by now, but v1.2.0 will hopefully fix your issue.

Here's a fork of your plunk showing it working:
http://plnkr.co/edit/U3z3Zm?p=preview

**Comment by dev-thinks** [comment]
Thanks for the followup. Yes. I made some patches to make it work.

I will see if I can replace with your latest version.

I see it is working now in your plnkr. let me close this bug for now 👍
