### ISSUE TITLE
Controller 'tabset', required by directive 'tab', can't be found!

### ISSUE THREAD

**Issue by reizyr** [mikejacobson/angular-bootstrap-scrolling-tabs#34]
Hello Mike,
I got the following error using 'scrolling-tabs-wrapper'.

Detailed error:
Error: [$compile:ctreq] Controller 'tabset', required by directive 'tab', can't be found!

 I have seen such a issue, I took the latest version of your directive (v0.0.30) ,but it didn't help.

angularjs: v1.3.19

Code:
   <div class="fullHeight">
        <div scrolling-tabs-wrapper="">
            <tabset class="fullHeight">
                <tab heading="Personal" ng-show="!hiddenTabs[Personal]" active="metaData[0].active">
                    <div ng-show="!hiddenTabs[Personal]">
                    </div>
                </tab>
                <tab heading="Log Info" ng-show="!hiddenTabs[Log_Info]" active="metaData[3].active">
                    <div ng-show="!hiddenTabs[Log_Info]">
                 </div>
                </tab>
            </tabset>
        </div>
    </div>

**Comment by reizyr** [comment]
Sorry, the code was cut. Here is my code:

    <div class="fullHeight">
        <div scrolling-tabs-wrapper="">
            <tabset class="fullHeight">
                <tab heading="Personal" ng-show="!hiddenTabs[Personal]" active="metaData[0].active">
                    <div ng-show="!hiddenTabs[Personal]">
                    </div>
                </tab>
                <tab heading="Log Info" ng-show="!hiddenTabs[Log_Info]" active="metaData[3].active">
                    <div ng-show="!hiddenTabs[Log_Info]">
                 </div>
                </tab>
            </tabset>
        </div>
    </div>

**Comment by mikejacobson** [comment]
If you could put together a plunk that demonstrates the issue, that would be very helpful. Maybe fork one of the plunks from the README and update it with your scenario (including the version of angular and angular-ui you're using)?

I've seen this error before when the `scrolling-tabs-wrapper` directive wasn't able to recognize that it was wrapping an angular-ui tabset. Specifically, at line 837 of `scrolling-tabs.js`, variable `isWrappingAngularUITabset` was getting set to `false` because the expected child elements that would indicate an angular-ui tabset weren't being found (because they were not in the DOM due to an `ng-if`, I believe).

So you might want to look at that and make sure that variable is getting set to `true`.
