### ISSUE TITLE
Refresh elements size on containers size change

### ISSUE THREAD

**Issue by lukasoberhoeller** [mikejacobson/angular-bootstrap-scrolling-tabs#37]
If the containers size changed, the elements size aren't recalculated so the the tab control will not be rendered correctly.
A window size change or the change of the tab collection is required to render the control correctly.

Here a plunker to reproduce the issue:
http://plnkr.co/edit/xN40AmjVc9npecQdF89E?p=preview

thank you

**Comment by mikejacobson** [comment]
Right, I had the same issue with the jQuery plugin version of this. Since there's not really a good way to detect a change in the container size, I created a `refresh` method that could be called by the user code any time they changed the container size.

I'm thinking I'll need to add something similar to this. So in your example plunk, you'd need to call that `refresh` (or whatever it's going to be) when the Full/Half button is clicked.

**Comment by lukasoberhoeller** [comment]
Thanks for your reply!
A refresh method would be great!

**Comment by mikejacobson** [comment]
For v0.1.0, I added a `refresh-on` option, so you can point that attribute to a flag that it will watch, and when that flag is truthy the tabs container will refresh its sizes.

Details in the README [here](https://github.com/mikejacobson/angular-bootstrap-scrolling-tabs#refreshOn).

And here's a fork of your plunk showing it working:
http://plnkr.co/edit/bdqMZPyQbt0TmKZAYybK

**Comment by lukasoberhoeller** [comment]
Thank you!
