### ISSUE TITLE
Dynamic Tabs Issue

### ISSUE THREAD

**Issue by damianpickwell** [mikejacobson/angular-bootstrap-scrolling-tabs#4]
I'm having an issue when adding tabs dynamically. The new tabs seem to be added vertically and upon resizing the width of the window they jump into place horizontally and everything works as expected. 

Any chance you could take a look for me and point me in the right direction. Created a plunker here http://plnkr.co/edit/IkkXut?p=preview

Thanks

**Comment by mikejacobson** [comment]
Funny, just minutes ago, based on another request, I checked in an update that handles dynamically-added tabs. I forked your plunk with the latest code:
http://plnkr.co/edit/2WnUV5l2cMqiGUr4Olyt?p=preview

To make it work, you need to add a `watch-tabs` attribute to the `scrolling-tabs-wrapper` directive element.

The update was mostly for using AngularUI tabset but it also works if you're wrapping regular Bootstrap tabs, provided that each new tab you add dynamically is not going to default to be the active tab. I'm still working on making it work for that scenario. But it looks like it's working for yours since you're not defaulting the new tabs to active.

Let me know if you have any problems.

Mike

**Comment by damianpickwell** [comment]
Just dropped it into my project and the changes work brilliantly.

Thanks for such a quick response :+1:

**Comment by mikejacobson** [comment]
Latest commit (v0.0.12) provides a more complete solution for this. Dynamically added tabs are now supported by both the `scrolling-tabs` and `scrolling-tabs-wrapper` directives. And they both handle the newly-added tab being the active tab.
