### ISSUE TITLE
Mobile swipe gesture to scroll through tabs?

### ISSUE THREAD

**Issue by cathal-killeen** [mikejacobson/angular-bootstrap-scrolling-tabs#44]
I'm trying to allow touch gestures to scroll through the tabs when on a mobile device. I'm not sure how to enable/implement this though. Currently the only way to scroll through the tabs is to click the two side buttons, but it would be much more intuitive to simply swipe through them.

**Comment by mikejacobson** [comment]
v1.1.0 adds support for touch swiping, with the caveat that it's really only practical for WebKit-based browsers, otherwise you'll have a visible horizontal scrollbar.

Details in the README here:
https://github.com/mikejacobson/angular-bootstrap-scrolling-tabs#allowScrollbar

I hope this gives you what you need.

**Comment by cathal-killeen** [comment]
Thanks!
