### ISSUE TITLE
[Enhancement] Display only full tabs

### ISSUE THREAD

**Issue by loht** [mikejacobson/angular-bootstrap-scrolling-tabs#5]
Is it possible to enhance the scrolling tabs such that there is an option to only show full tabs (No partial tabs shown next to the arrows)?

**Comment by mikejacobson** [comment]
I'll look into it. Seems like it should be possible...

**Comment by mikejacobson** [comment]
OK, my latest commit, v0.0.14, adds support for this feature.

Just add attribute `scroll-to-tab-edge="true"` to the directive element to ensure scrolling always ends with a tab edge aligned with the left scroll arrow. (I couldn't guarantee full tabs on both the left and right sides because that's dependent on the width of the tabs and the window.)

[Here's the description.](https://github.com/mikejacobson/angular-bootstrap-scrolling-tabs#ft2)

Thanks for the suggestion!
