### ISSUE TITLE
Move to new version of Angular

### ISSUE THREAD

**Issue by newmanw** [mikejacobson/angular-bootstrap-scrolling-tabs#6]
2 versions behind @ 1.2

**Comment by mikejacobson** [comment]
I've actually been keeping it at 1.2 because I had a business requirement to make it work in IE8, and 1.2 is the latest version that supports IE8. I figured I'd keep it there in case any others were also stuck supporting IE8. That's just the minimum required version, though--it works with 1.3 and 1.4 also.
